'use client';

import {ArrowRight,Gamepad2,Trophy,Users} from 'lucide-react';

export function PlayLaunchpad({practice,quickSeat,hasSeat,loading,address,credits,totals}:{practice:()=>void;quickSeat:()=>void;hasSeat:boolean;loading:boolean;address?:string;credits?:bigint;totals?:readonly bigint[]}) {
  const rank=credits!==undefined&&totals?totals.filter(total=>total>credits).length+1:undefined;
  const nextTotal=credits!==undefined&&totals?totals.filter(total=>total>credits).reduce<bigint|undefined>((min,total)=>min===undefined||total<min?total:min,undefined):undefined;
  const wins=nextTotal!==undefined&&credits!==undefined?nextTotal-credits+1n:undefined;
  return <section className="mb-6 grid gap-4 lg:grid-cols-[1.5fr_1fr]">
    <div className="border-3 border-ink bg-acid p-5 shadow-hard sm:p-6"><p className="eyebrow">TWO CARDS. ONE GOOD DECISION.</p><h2 className="mt-3 font-heading text-3xl sm:text-4xl">Poker starts here.</h2><p className="mt-3 max-w-xl text-sm font-semibold">New to poker? Play a computer opponent instantly and learn as you go. Ready for friends? Find a table and win your first Credit.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={practice} className="brutal-button bg-ink px-3 py-4 text-white"><Gamepad2 className="size-5"/>Play instantly</button><button disabled={loading} onClick={quickSeat} className="brutal-button bg-white px-3 py-4 disabled:opacity-50"><Users className="size-5"/>{loading?'Finding tables…':hasSeat?'Find me a seat':'Start a friends table'}</button></div><p className="mt-3 text-xs font-semibold">Practice: no wallet, no waiting. Multiplayer: free play chips; test ETH needed for network fees.</p></div>
    <div className="border-3 border-ink bg-purple p-5 text-white shadow-hard"><Trophy className="size-8 text-acid"/><h2 className="mt-4 font-heading text-2xl">Your next win matters.</h2><p className="mt-2 text-sm">Each completed multiplayer hand awards every winning player +1 Credit. Small tables earn the same Credit as big tables.</p><div className="mt-4 border-2 border-white/40 p-3"><p className="font-mono text-[10px] text-acid">YOUR NEXT TARGET</p><strong className="mt-1 block text-xl">{!address?'Win your first Credit':credits===undefined||!totals?'Loading your standing…':credits===0n?'1 win gets you on the board':wins!==undefined?`${wins} ${wins===1n?'win':'wins'} to pass the next score`:'Defend your lead'}</strong>{rank!==undefined&&credits!==undefined&&credits>0n&&<p className="mt-1 text-xs">Competition rank #{rank} · {credits.toString()} Credits{wins!==undefined?' · target based on current scores':''}</p>}</div><button onClick={practice} className="mt-3 flex min-h-11 items-center gap-2 text-sm font-bold">Learn the moves first <ArrowRight className="size-4"/></button></div>
  </section>;
}
