import {BookOpen,CheckCircle2} from 'lucide-react';

export function TableGuide({phase,seated,host,players,submitted,batches,myTurn,due,boardPending,folded,allIn,busy}:{phase:number;seated:boolean;host:boolean;players:number;submitted:boolean;batches:number;myTurn:boolean;due:number;boardPending:boolean;folded:boolean;allIn:boolean;busy:boolean}) {
  let title='Take a seat to play';let body='Joining gives you the table’s free play chips. Your wallet confirmation pays only the testnet network fee.';
  if(phase===8){title='This table has closed';body='Go back to the lobby to find a fresh table.';}
  else if(!seated&&phase>0&&phase<7){title='You’re watching a hand';body='You can join once this hand finishes. Shared cards and public moves are visible while you watch.';}
  else if(seated&&(phase===0||phase===7)){title=players<2?'Bring a friend to the table':host?'Ready for the next hand':'Waiting for the host';body=players<2?'Copy the invite link below and send it to a friend. Two funded players are enough to start.':host?'Press Start hand below. Then each player readies their private cards.':'The host starts the hand. Keep this table open; it updates automatically.';}
  else if(seated&&phase===1){title=batches>0?'The private deck is being dealt':submitted?'You’re ready':'Ready your private cards';body=batches>0?`Press Deal next batch below. ${batches} wallet ${batches===1?'confirmation remains':'confirmations remain'} for this deal; either player can help.`:submitted?'The other players still need to ready their cards. You do not need to sign again yet.':'Press Ready my private cards once. Your wallet helps create a deal that no single player controls.';}
  else if(seated&&phase===6){title='Time to find the winner';body='Press Show winner below to verify the final hands and award the pot and Credits. Only one player needs to complete this.';}
  else if(seated&&boardPending){title='Reveal the shared cards';body='Press Reveal below to open the next shared cards for everyone. Betting resumes after confirmation.';}
  else if(seated&&folded){title='You folded this hand';body='Your remaining chips are safe. Watch how the hand plays out and join the next deal.';}
  else if(seated&&allIn){title='You’re all-in';body='Your chips are in the pot. No more betting is needed from you. Shared cards and the winner still need to be revealed.';}
  else if(seated&&myTurn){title=due?`Your move · ${due} chips to stay in`:'Your move · checking is free';body='Check or call to stay in. Raise to put more chips in. Fold to leave this hand. The pot goes to the best five cards, or the last player who stays.';}
  else if(seated){title='Your rival is thinking';body='You can view your cards while you wait. Your action buttons appear when it’s your turn.';}
  if(busy){title='One move is processing';body='Approve the request in your wallet if prompted. The table will update after confirmation; no need to press again.';}
  return <div className="border-2 border-acid bg-ink p-3 text-white sm:p-4" aria-live="polite"><p className="flex items-center gap-2 font-black text-acid"><CheckCircle2 className="size-5 shrink-0"/>{title}</p><p className="mt-1 text-sm leading-relaxed text-white/80">{body}</p><details className="mt-2 text-xs"><summary className="flex min-h-9 cursor-pointer items-center gap-1 font-bold"><BookOpen className="size-3"/>How do I win?</summary><p className="mt-1 max-w-3xl leading-relaxed">Build the best five-card hand using your two cards and the five shared cards. Strongest first: straight flush, four of a kind, full house, flush, straight, three of a kind, two pair, pair, high card. If everyone else folds, you win immediately. Winning a settled multiplayer hand gives +1 Credit; practice games do not.</p></details></div>;
}
