import {BookOpen,CheckCircle2} from 'lucide-react';

export function TableGuide({phase,seated,host,players,full,submitted,batches,myTurn,due,boardPending,folded,allIn,busy}:{phase:number;seated:boolean;host:boolean;players:number;full:boolean;submitted:boolean;batches:number;myTurn:boolean;due:number;boardPending:boolean;folded:boolean;allIn:boolean;busy:boolean}) {
  let title='Take a seat to play';let body='Joining gives you the table’s free play chips. Your wallet confirmation pays only the testnet network fee.';
  if(phase===8){title='This table has closed';body='Go back to the lobby to find a fresh table.';}
  else if(!seated&&full&&(phase===0||phase===7)){title='Table full · watching';body='These seats are occupied. You can watch, or return to the lobby to find an open seat.';}
  else if(!seated&&phase>0&&phase<7){title='You’re watching a hand';body='You can join once this hand finishes. Shared cards and public moves are visible while you watch.';}
  else if(seated&&(phase===0||phase===7)){title=players<2?'Bring a friend to the table':host?'Ready for the next hand':'Waiting for the host';body=players<2?'Copy the invite link below and send it to a friend. Two funded players are enough to start.':host?'Press Start hand below. Then each player readies their private cards.':'The host starts the hand. Keep this table open; it updates automatically.';}
  else if(seated&&phase===1){title=batches>0?'The private deck is being dealt':submitted?'You’re ready':'Ready your private cards';body=batches>0?(batches===1?'Press Deal all cards below. The remaining encrypted deal is combined into one wallet confirmation. Either player can help.':`Smaller-batch mode: ${batches} confirmations remain. You can switch back to Deal all cards below.`):submitted?'The other players still need to ready their cards. You do not need to sign again yet.':'Press Ready my private cards once. Your wallet helps create a deal that no single player controls.';}
  else if(seated&&phase===6){title='Time to find the winner';body='Press Show winner below to verify the final hands and award the pot and Credits. Only one player needs to complete this.';}
  else if(seated&&boardPending){title='Reveal the shared cards';body='Press Reveal below to open the next shared cards for everyone. Betting resumes after confirmation.';}
  else if(seated&&folded){title='You folded this hand';body='Your remaining chips are safe. Watch how the hand plays out and join the next deal.';}
  else if(seated&&allIn){title='You’re all-in';body='Your chips are in the pot. No more betting is needed from you. Shared cards and the winner still need to be revealed.';}
  else if(seated&&myTurn){title=due?`Your move · ${due} chips to stay in`:'Your move · checking is free';body='Check or call to stay in. Raise to put more chips in. Fold to leave this hand. The pot goes to the best five cards, or the last player who stays.';}
  else if(seated){title='Your rival is thinking';body='You can view your cards while you wait. Your action buttons appear when it’s your turn.';}
  if(busy){title='One move is processing';body='Approve the request in your wallet if prompted. The table will update after confirmation; no need to press again.';}
  return <details className="table-guide border border-acid/60 bg-ink px-3 text-white"><summary className="flex min-h-10 cursor-pointer items-center justify-between gap-2 text-xs font-black text-acid"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 shrink-0"/>{title}</span><span className="flex shrink-0 items-center gap-1 text-white/65"><BookOpen className="size-3"/>Help</span></summary><p className="pb-2 text-xs leading-relaxed text-white/80">{body}</p><p className="pb-3 text-xs text-white/60">Make the best five-card hand from your cards and the board, or win when everyone else folds. Only completed multiplayer wins award Credits.</p></details>;
}
